# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('1v1', '1 vs 1'), ('athletics', 'Athletics'), ('team', 'Team')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=1000)),
                ('team_A', models.CharField(max_length=50)),
                ('team_B', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
            ],
        ),
    ]
