# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_event_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='winner',
        ),
    ]
