# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_event_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='winner',
            field=models.CharField(max_length=20),
        ),
    ]
